basePath: "/v1"
tags:
  - name: "loanApp"
    description: "Api Documentation for Loan App"
schemes:
  - "http"
  - "https"



definitions:
  ReqAddCompany:
    properties:
      first_name:
        description: |-
          First Name
           in: string
        type: string
        x-go-name: first_name
      last_name:
        description: |-
          Last Name
          in: string
        format: string
        type: string
        x-go-name: last_name
      phone:
        description: |-
          Phone
          in: string
        format: string
        type: string
        x-go-name: phone
      email:
        description: |-
          Email
          in: string
        format: string
        type: string
        x-go-name: email
      password:
        description: |-
          Password
          in: string
        format: string
        type: string
        x-go-name: password
    type: object
    x-go-package: goswagger/models
host: localhost:4000
info:
  title: 'Loan App Api Backend'
  version: 0.0.1
paths:
  /signup:
    post:
      description: Signup A User
      operationId: Signup A User
      parameters:
        - description: 'name: body'
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ReqAddCompany'
          x-go-name: Body
      responses:
        "200":
          description: GetCompany
          schema:
            $ref: '#/definitions/ReqAddCompany'
        "400":
          description: CommonError
          schema:
            $ref: '#/definitions/ReqAddCompany'


produces:
  - application/json

securityDefinitions:
  apiKey:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"