basePath: "/v1"
tags:
  - name: "loanApp"
    description: "Api Documentation for Loan App"
schemes:
  - "http"
  - "https"



definitions:
  SignupRequest:
    properties:

      phone:
        description: |-
          Phone
          in: string
        format: string
        type: string
        x-go-name: phone

    type: object
    x-go-package: goswagger/models

  ContactUploadRequest:
    properties:

      loan_id:
        description: |-
          Loan Id
          in: number
        format: number
        type: number
        x-go-name: loan_id

      contacts:
        description: |-
          Contacts In Stringified
          in: string
        format: string
        type: string
        x-go-name: string

    type: object
    x-go-package: goswagger/models

  AdminLoginRequest:
    properties:

      username:
        description: |-
          Username
          in: string
        format: string
        type: string
        x-go-name: phone
      password:
        description: |-
          Password
          in: string
        format: string
        type: string
        x-go-name: phone

    type: object
    x-go-package: goswagger/models
  LoginRequest:
    properties:
      phone:
        description: |-
          Phone
          in: string
        format: string
        type: string
        x-go-name: email
      otp:
        description: |-
          OTP
          in: string
        format: string
        type: string
        x-go-name: password
    type: object
    x-go-package: goswagger/models

host: 23.92.65.116:8090
info:
  title: 'Loan App Api Backend'
  version: 0.0.1
paths:
  /signup:
    post:
      description: Signup A User
      operationId: Signup A User
      parameters:
        - description: 'name: body'
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SignupRequest'
          x-go-name: Body
      responses:
        "200":
          description: Signup
          schema:
            $ref: '#/definitions/SignupRequest'
        "400":
          description: CommonError
          schema:
            $ref: '#/definitions/SignupRequest'
  /login:
    post:
      description: Signup A User
      operationId: Login A User
      parameters:
        - description: 'name: body'
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
          x-go-name: Body
      responses:
        "200":
          description: SuccessFull Login
          schema:
            $ref: '#/definitions/LoginRequest'
        "400":
          description: CommonError
          schema:
            $ref: '#/definitions/LoginRequest'

  /admin/login:
    post:
      description: Login Admin
      operationId: Login Admin
      parameters:
        - description: 'name: body'
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/AdminLoginRequest'
          x-go-name: Body
      responses:
        "200":
          description: SuccessFull Login
          schema:
            $ref: '#/definitions/AdminLoginRequest'
        "400":
          description: CommonError
          schema:
            $ref: '#/definitions/AsdminLoginRequest'
  /admin/loandata:
    get:
      description: Get Loan Applications
      operationId: Login Admin

      responses:
        "200":
          description: Loan Applications

        "400":
          description: CommonError


  /verified/contactupload:
    post:
      description: Upload Contacts Of User
      operationId: Upload Contacts Of User
      parameters:
        - in: header
          name: token
          schema:
          type: string
          format: string
          required: true
        - description: 'name: body'
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ContactUploadRequest'
          x-go-name: Body


      responses:
        "200":
          description: Loan Applications

        "400":
          description: CommonError



  /verified/formdata:
    post:
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      parameters:
        - in: header
          name: token
          schema:
          type: string

          required: true

        - in: formData
          name: uploadfile
          type: file
          description: The file to upload.

        - in: formData
          name: first_name
          type: string
          required: true
          description: First Name.

        - in: formData
          name: middle_name
          type: string
          required: false
          description: MiddleName .

        - in: formData
          name: sur_name
          type: string
          required: true
          description: Sur Name.


        - in: formData
          name: gender
          type: string
          required: true
          description: Gender.

        - in: formData
          name: pan_number
          type: string
          required: true
          description: Pan Number.

        - in: formData
          name: birthday
          type: string
          required: true
          description: Birthday.


      responses:
        "200":
          description: SuccessFully Created


produces:
  - application/json

securityDefinitions:
  apiKey:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"